# ETS2-AI training kernel (auto-generated by ets2-ai/kaggle/build_kernel.py)
# Same code, same seed as the repo — output is validated by GitHub Actions.

# ===== ets2ai/contract.py =====
"""Shared feature/action contract for the ETS2-AI driving policy.

Every implementation (numpy training, Java on-device, TFLite, Windows bridge)
must obey EXACTLY this contract. Changing it requires regenerating weights.
"""
import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Input features (12). Order is part of the wire format.
# ---------------------------------------------------------------------------
FEATURES = [
    "speed",            # m/s / 25 (truck top speed ~ 25 m/s = 90 km/h)
    "lane_offset",      # lateral offset from lane centre, m / 3.5
    "heading_error",    # heading error vs road tangent, rad / 0.6
    "curv_1",           # curvature at 8 m ahead, 1/m / 0.05
    "curv_2",           # curvature at 18 m ahead
    "curv_3",           # curvature at 30 m ahead
    "curv_4",           # curvature at 45 m ahead
    "curv_5",           # curvature at 60 m ahead
    "speed_limit",      # speed limit, m/s / 25
    "fuel",             # fuel fraction 0..1
    "fatigue",          # fatigue 0..1 (1 = must sleep immediately)
    "job_dist",         # remaining job distance, km / 100
    "radar_dist",       # distance to the next speed camera, m / 500
]
N_IN = len(FEATURES)

# ---------------------------------------------------------------------------
# Outputs (3). Order is part of the wire format.
# ---------------------------------------------------------------------------
ACTIONS = ["steer", "throttle", "brake"]
N_OUT = len(ACTIONS)

# MLP architecture (part of the wire format).
HIDDEN = [290] * 13    # 1,017,613 parameters — narrow & deep (user spec v0.4.4)
SEED = 20260930  # deterministic training across runs/CI

# Reporting target demanded by the project brief.
LOSS_TARGET = 0.150


def clamp_action(steer, throttle, brake):
    """Actuator clamp — part of the wire contract (mirrored in Java/bridge).
    The raw MLP may extrapolate outside the training distribution; commands
    sent to the game (or the demo sim) are always clamped here."""
    return (max(-1.0, min(1.0, steer)),
            max(0.0, min(1.0, throttle)),
            max(0.0, min(1.0, brake)))


def model_meta(epochs=None, samples=None, loss=None, dtype=None):
    meta = {
        "features": FEATURES,
        "actions": ACTIONS,
        "hidden": HIDDEN,
        "seed": SEED,
        "loss_target": LOSS_TARGET,
        "epochs": epochs,
        "samples": samples,
        "final_loss": loss,
    }
    if dtype is not None:  # float32 (deploy) nao registra: mantem o JSON igual
        meta["dtype"] = dtype
    return meta


def save_weights(path, layer_weights, meta):
    """layer_weights: list of (W, b) numpy arrays; saved as plain JSON."""
    payload = {
        "meta": meta,
        "layers": [
            {"w": w.tolist(), "b": b.tolist()} for (w, b) in layer_weights
        ],
    }
    Path(path).write_text(json.dumps(payload), encoding="utf-8")


def load_weights(path):
    import numpy as np
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    layers = [
        (np.array(l["w"], dtype=np.float32), np.array(l["b"], dtype=np.float32))
        for l in payload["layers"]
    ]
    return layers, payload["meta"]


def save_device_format(path, layers, meta):
    """Plain-text weights for the Java app (no JSON parser on device).

    Format (CSV, one float per value, '.' decimal separator):
        ETS2AI,v1,<nin>,<nout>,<h1>,<h2>
        per layer: W rows (fan_in lines of fan_out floats), then bias line.
    The values are bit-identical to model-weights.json.
    """
    lines = [f"ETS2AI,v1,{N_IN},{N_OUT},{','.join(str(h) for h in HIDDEN)}"]
    for (w, b) in layers:
        for row in w:
            lines.append(",".join(repr(float(v)) for v in row))
        lines.append(",".join(repr(float(v)) for v in b))
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def load_device_format(path):
    """Reference loader (used by tests to prove txt == json)."""
    import numpy as np
    lines = Path(path).read_text(encoding="utf-8").strip().splitlines()
    header = lines[0].split(",")
    assert header[0] == "ETS2AI" and header[1] == "v1"
    sizes = [int(header[2])] + [int(h) for h in header[4:]] + [int(header[3])]
    layers, pos = [], 1
    for i in range(len(sizes) - 1):
        fan_in, fan_out = sizes[i], sizes[i + 1]
        w = np.zeros((fan_in, fan_out), dtype=np.float32)
        for r in range(fan_in):
            w[r] = [float(v) for v in lines[pos].split(",")]
            pos += 1
        b = np.array([float(v) for v in lines[pos].split(",")], dtype=np.float32)
        pos += 1
        layers.append((w, b))
    assert pos == len(lines)
    return layers
# ===== ets2ai/sim.py =====
"""ETS2-AI world model: road, truck physics, expert driver, career rules.

Deterministic, dependency-light, ported 1:1 to Java (SimWorld.java) and to the
Windows bridge demo so that the phone, the PC and the trainer all agree on
physics and the expert never disagrees with itself.
"""
import math
import numpy as np

DT = 0.1                 # simulation step (s)
WHEELBASE = 4.0          # m (kinematic bicycle)
MAX_STEER = 0.6          # rad at the wheels, scaled by |steer| command
MAX_ACCEL = 1.8          # m/s^2 at full throttle
MAX_BRAKE = 3.2          # m/s^2 at full brake
DRAG = 0.030             # rolling/aero deceleration factor per (m/s)
LAT_ACCEL_COMFORT = 2.4  # m/s^2 the expert accepts in curves
LAT_ACCEL_ROLLOVER = 3.6  # m/s^2 where a truck starts to roll over
ROLLOVER_MARGIN = 0.82    # the expert stays at 82% of the rollover limit
V_MAX = 36.0              # m/s (~130 km/h): speeding policy
RADAR_SLOW = 0.95         # fraction of the limit kept AT the camera
RADAR_BRAKE = 2.6         # m/s^2 deceleration budget before a camera
LANE_HALF = 2.0          # |offset| beyond this = off-lane
ROAD_HALF = 4.6          # |offset| beyond this = off-road (crash barrier)

FUEL_START = 1.0
FUEL_BURN_IDLE = 0.000012      # per second
FUEL_BURN_FULL = 0.000160      # per second at full throttle
FATIGUE_START = 0.0
FATIGUE_RATE = 1.0 / (11 * 3600)   # ~11 h of driving to full fatigue
REFUEL_BELOW = 0.14
SLEEP_ABOVE = 0.82
FUEL_PRICE = 1.45              # EUR / L  (tank modelled as fraction)
TANK_LITERS = 600
SLEEP_HOURS = 9
SPEED_LIMIT_MPS = 25.0         # 90 km/h truck limit

LOOKAHEAD = (8.0, 18.0, 40.0, 90.0, 170.0)
PURE_PURSUIT_DIST = 12.0


# ---------------------------------------------------------------------------
# Road: piecewise-constant-curvature ribbon, seeded deterministically.
# ---------------------------------------------------------------------------
class Road:
    def __init__(self, seg_lengths, seg_curvs):
        self.seg_lengths = [float(v) for v in seg_lengths]
        self.seg_curvs = [float(v) for v in seg_curvs]
        self.cum = [0.0]
        for L in self.seg_lengths:
            self.cum.append(self.cum[-1] + L)
        self.length = self.cum[-1]
        self.radars = []
        # integrate centreline
        pts = [(0.0, 0.0)]
        hdg = 0.0
        step = 2.0
        s = 0.0
        self.samples = [pts[0]]
        self.sample_s = [0.0]
        while s < self.length:
            s = min(s + step, self.length)
            hdg += self.curvature_at(s) * step
            x, y = self.samples[-1]
            self.samples.append((x + step * math.cos(hdg),
                                 y + step * math.sin(hdg)))
            self.sample_s.append(s)

    @staticmethod
    def random(seed, n_seg=40, min_len=60.0, max_len=420.0, max_curv=0.012):
        rng = np.random.default_rng(seed)
        lens = rng.uniform(min_len, max_len, n_seg)
        curvs = []
        for _ in range(n_seg):
            r = rng.uniform()
            if r < 0.35:                    # straight
                curvs.append(0.0)
            else:
                curvs.append(float(rng.uniform(-max_curv, max_curv)))
        road = Road(lens, curvs)
        # speed cameras along the route (the "radars")
        rng2 = np.random.default_rng(seed + 777)
        radars = []
        pos = 700.0
        while pos < road.length - 150.0:
            radars.append(pos)
            pos += float(rng2.uniform(1500.0, 2800.0))
        road.radars = radars
        return road

    def upcoming_curves(self, s, max_dist=260.0):
        """[(distance_to_start, |kappa|)] of curves ahead, in road order."""
        out = []
        for i, k in enumerate(self.seg_curvs):
            seg_start, seg_end = self.cum[i], self.cum[i + 1]
            if seg_end <= s:
                continue
            d = max(0.0, seg_start - s)
            if d > max_dist:
                break
            if abs(k) > 1e-6:
                out.append((d, abs(k)))
        return out

    def radar_dist_ahead(self, s):
        """Metres to the next camera ahead of s (500 = none ahead)."""
        best = 500.0
        for r in self.radars:
            d = r - s
            if 0.0 < d < best:
                best = d
        return best

    def curvature_at(self, s):
        s = max(0.0, min(s, self.length - 1e-6))
        for i, L in enumerate(self.seg_lengths):
            if s <= self.cum[i + 1] + 1e-9:
                return self.seg_curvs[i]
        return 0.0

    def project(self, x, y, hint=None):
        """Closest centreline sample -> (s, offset, tangent_heading).

        `hint`: last sample index; searches a local window first (the truck
        moves a few metres per step). Falls back to a full scan. Same
        behaviour in the Java port.
        """
        samples = self.samples
        n = len(samples)
        if hint is not None:
            lo, hi = max(0, hint - 40), min(n, hint + 40)
            best_i, best_d2 = None, float("inf")
            for i in range(lo, hi):
                px, py = samples[i]
                d2 = (px - x) ** 2 + (py - y) ** 2
                if d2 < best_d2:
                    best_i, best_d2 = i, d2
            if best_i is not None and best_d2 < (30.0 ** 2):
                return self._project_at(best_i, x, y)
        best_i, best_d2 = 0, float("inf")
        for i, (px, py) in enumerate(samples):
            d2 = (px - x) ** 2 + (py - y) ** 2
            if d2 < best_d2:
                best_i, best_d2 = i, d2
        return self._project_at(best_i, x, y)

    def _project_at(self, best_i, x, y):
        s = self.sample_s[best_i]
        i0 = max(0, best_i - 2)
        i1 = min(len(self.samples) - 1, best_i + 2)
        tx = self.samples[i1][0] - self.samples[i0][0]
        ty = self.samples[i1][1] - self.samples[i0][1]
        tn = math.hypot(tx, ty) or 1.0
        tx, ty = tx / tn, ty / tn
        dx, dy = x - self.samples[best_i][0], y - self.samples[best_i][1]
        offset = dx * -ty + dy * tx
        return s, offset, math.atan2(ty, tx)


# ---------------------------------------------------------------------------
# Truck state + physics step (identical in Java/Python).
# ---------------------------------------------------------------------------
class Truck:
    def __init__(self, road, s=0.0, offset=0.0, speed=15.0, heading=None):
        self.s = s
        self._hint = 0
        x, y, th = road_point(road, s)
        # start on the lane line given by offset (positive = right of centre)
        self.x = x - offset * math.sin(th)
        self.y = y + offset * math.cos(th)
        self.s, self.offset, self.tangent = self.project(road)
        self.heading = self.tangent if heading is None else heading
        self.speed = speed
        self.steer_pos = 0.0  # smoothed actual steering, for features
        self.fuel = FUEL_START
        self.fatigue = FATIGUE_START
        self.money = 0.0
        self.driven_km = 0.0

    def project(self, road):
        """Fast re-projection using a moving window (kept in Java too)."""
        samples = road.samples
        n = len(samples)
        best_i, best_d2 = self._hint, float("inf")
        for i in range(max(0, self._hint - 40), min(n, self._hint + 40)):
            px, py = samples[i]
            d2 = (px - self.x) ** 2 + (py - self.y) ** 2
            if d2 < best_d2:
                best_i, best_d2 = i, d2
        if best_d2 > 30.0 ** 2:
            return road.project(self.x, self.y)   # full scan fallback
        self._hint = best_i
        return road._project_at(best_i, self.x, self.y)

    def step(self, road, steer, throttle, brake, dt=DT):
        steer = max(-1.0, min(1.0, steer))
        throttle = max(0.0, min(1.0, throttle))
        brake = max(0.0, min(1.0, brake))
        # steering actuator: rack moves toward command
        self.steer_pos += max(-0.15, min(0.15, steer - self.steer_pos))
        wheel = self.steer_pos * MAX_STEER
        self.heading += (self.speed / WHEELBASE) * math.tan(wheel) * dt
        self.x += self.speed * math.cos(self.heading) * dt
        self.y += self.speed * math.sin(self.heading) * dt
        acc = throttle * MAX_ACCEL - brake * MAX_BRAKE - DRAG * self.speed
        self.speed = max(0.0, self.speed + acc * dt)
        self.driven_km += self.speed * dt / 1000.0
        self.fuel = max(0.0, self.fuel - dt *
                        (FUEL_BURN_IDLE + throttle * (FUEL_BURN_FULL - FUEL_BURN_IDLE)))
        self.fatigue = min(1.0, self.fatigue + dt * FATIGUE_RATE)
        self.s, self.offset, self.tangent = self.project(road)


def road_point(road, s):
    """(x, y, heading) of centreline near arclength s (nearest sample)."""
    i = min(range(len(road.sample_s)), key=lambda k: abs(road.sample_s[k] - s))
    th = heading_at(road, i)
    x, y = road.samples[i]
    return x, y, th


def heading_at(road, i):
    i0, i1 = max(0, i - 1), min(len(road.samples) - 1, i + 1)
    return math.atan2(road.samples[i1][1] - road.samples[i0][1],
                      road.samples[i1][0] - road.samples[i0][0])


# ---------------------------------------------------------------------------
# Features / actions (the contract in numbers).
# ---------------------------------------------------------------------------
def features(road, truck, job_left_km):
    s, offset, tangent = truck.project(road)
    hdg_err = wrap_angle(truck.heading - tangent)
    curvs = [road.curvature_at(s + d) / 0.05 for d in LOOKAHEAD]
    return [
        truck.speed / 25.0,
        offset / 3.5,
        hdg_err / 0.6,
        curvs[0], curvs[1], curvs[2], curvs[3], curvs[4],
        SPEED_LIMIT_MPS / 25.0,
        truck.fuel,
        truck.fatigue,
        min(job_left_km, 20.0) / 20.0,
        road.radar_dist_ahead(s) / 500.0,
    ]


def wrap_angle(a):
    while a > math.pi:
        a -= 2 * math.pi
    while a < -math.pi:
        a += 2 * math.pi
    return a


# ---------------------------------------------------------------------------
# Rollover governor (ESC-like): caps speed so v^2 * |kappa| stays below the
# rollover limit. The net proposes; the governor guarantees the physics.
# Mirrored in SimWorld.java and in the bridge.
# ---------------------------------------------------------------------------
GOVERNOR_LIMIT = 0.92 * LAT_ACCEL_ROLLOVER


def governor(road, truck, cmd):
    """ESC: full brake if the current speed cannot be shed before the START
    of any curve ahead (brake planned to real curve-start distance)."""
    worst = None
    for d, k in road.upcoming_curves(truck.s):
        v_curve = math.sqrt(GOVERNOR_LIMIT / k)
        v_allow = math.sqrt(v_curve ** 2 + 2.0 * MAX_BRAKE * max(0.0, d - 8.0))
        if worst is None or v_allow < worst:
            worst = v_allow
    if worst is not None and truck.speed > worst:
        return (cmd[0], 0.0, 1.0)  # full brake: safety over comfort
    # dock governor: never carry speed into the loading dock (full distance)
    d_dock = (road.length - 6.0) - truck.s
    if 0.0 < d_dock < 600.0:
        v_allow = math.sqrt(2.0 * MAX_BRAKE * max(0.0, d_dock - 2.0))
        if truck.speed > v_allow + 0.3:
            return (cmd[0], 0.0, 1.0)
        if d_dock <= 1.5:
            return (cmd[0], 0.0, 1.0)               # hold at the line
        if d_dock < 600.0 and truck.speed < 2.0:
            return (cmd[0], max(cmd[1], 0.35), 0.0)  # creep: never stall short
    # anti-stall: nunca parar fora da linha de entrega. Todo job comeca do
    # zero (motor ligando) e a rede pode nao ter visto speed~0 no treino.
    if truck.speed < 0.6 and d_dock > 4.0:
        return (cmd[0], max(cmd[1], 0.35), 0.0)
    return cmd


# ---------------------------------------------------------------------------
# Expert driver: pure-pursuit steering + predictive speed control.
# ---------------------------------------------------------------------------
def expert(road, truck, job_left_km, noise=0.0, rng=None):
    s, offset, tangent = truck.project(road)
    tx, ty = math.cos(tangent), math.sin(tangent)
    d = PURE_PURSUIT_DIST
    gs = s + d
    gx = road_point(road, gs)[0] if gs <= road.length else None
    # target point on centreline ahead
    i = min(range(len(road.sample_s)), key=lambda k: abs(road.sample_s[k] - gs))
    px, py = road.samples[i]
    hdg_err = wrap_angle(truck.heading - tangent)
    lat_err = offset
    # pure pursuit: steer toward eliminating combined error
    alpha = math.atan2(-lat_err, d) - hdg_err
    steer = 2.0 * math.sin(alpha) / max(d, 1e-3) * 12.0
    steer = max(-1.0, min(1.0, steer))
    # speed target: as fast as possible WITHOUT ROLLING OVER — planning the
    # brake against the real distance to each curve START (not sample points).
    v_target = V_MAX
    a_lat = LAT_ACCEL_ROLLOVER * ROLLOVER_MARGIN
    for d, k in road.upcoming_curves(s):
        v_curve = min(V_MAX, math.sqrt(a_lat / k))
        v_allow = math.sqrt(v_curve ** 2 + 2.0 * RADAR_BRAKE * max(0.0, d - 12.0))
        v_target = min(v_target, v_allow)
    # dock: precise stop at the end of the route — continuous profile that
    # begins easing off hundreds of metres out (a fixed window cannot shed
    # 130 km/h in 130 m; physics decides the distance, not a constant).
    d_dock = (road.length - 6.0) - s
    if d_dock < 600.0:
        v_target = min(v_target, math.sqrt(2.0 * 1.6 * max(0.0, d_dock)))
        if v_target < 0.4:
            v_target = 0.0
    # radar: only slow down within braking distance of the camera
    d_radar = road.radar_dist_ahead(s)
    v_radar = SPEED_LIMIT_MPS * RADAR_SLOW
    brake_dist = max(0.0, truck.speed ** 2 - v_radar ** 2) / (2.0 * RADAR_BRAKE) + 25.0
    if d_radar < brake_dist:
        v_target = min(v_target, v_radar)
    # fatigue makes the expert ease off slightly (safe behaviour to imitate)
    v_target *= (1.0 - 0.08 * truck.fatigue)
    dv = v_target - truck.speed
    throttle = max(0.0, min(1.0, dv / 1.8))
    brake = max(0.0, min(1.0, -dv / 2.6))
    if noise and rng is not None:
        steer = max(-1.0, min(1.0, steer + rng.normal(0, noise)))
        throttle = max(0.0, min(1.0, throttle + rng.normal(0, noise * 0.5)))
        brake = max(0.0, min(1.0, brake + rng.normal(0, noise * 0.5)))
    return steer, throttle, brake


# ---------------------------------------------------------------------------
# Closed-loop episode runner (used for data generation AND evaluation).
# ---------------------------------------------------------------------------
def run_episode(road, policy, seed=0, max_steps=7000, noise=0.0,
                record=False, start_jitter=True):
    """policy(road, truck, job_left_km) -> (steer, throttle, brake)."""
    rng = np.random.default_rng(seed)
    if start_jitter:
        truck = Truck(road, s=5.0,
                      offset=float(rng.uniform(-2.0, 2.0)),
                      speed=float(rng.uniform(8.0, 22.0)))
        truck.heading += float(rng.uniform(-0.25, 0.25))
    else:
        truck = Truck(road, s=5.0, offset=0.0, speed=15.0)
    job_km = road.length / 1000.0
    feats, acts = [], []
    in_lane = off_road = 0
    stopped = False
    steps = 0
    radar_pass = []          # speeds AT each camera
    max_lat = 0.0            # max lateral acceleration (rollover watch)
    off_sum = 0.0
    docked = False
    stop_error_m = None
    while steps < max_steps:
        s, offset, _ = truck.project(road)
        d_dock = (road.length - 6.0) - s
        if d_dock <= 4.0 and truck.speed < 0.6:      # parked AT the line
            break
        if s >= road.length - 1.0:
            break
        job_left = max(0.0, (road.length - s) / 1000.0)
        steer, throttle, brake = policy(road, truck, job_left, rng)
        steer, throttle, brake = governor(road, truck, (steer, throttle, brake))
        if record:
            feats.append(features(road, truck, job_left))
            acts.append([steer, throttle, brake])
        prev_s = s
        truck.step(road, steer, throttle, brake)
        steps += 1
        d_dock_now = (road.length - 6.0) - truck.s
        if d_dock_now <= 4.0 and truck.speed < 0.6:
            docked = True
            stop_error_m = d_dock_now
            break
        if truck.s >= road.length - 1.0:
            stop_error_m = (road.length - 6.0) - truck.s   # overshoot
            break
        for r in road.radars:                     # crossed a camera?
            if prev_s < r <= truck.s:
                radar_pass.append(truck.speed)
        max_lat = max(max_lat, truck.speed ** 2 * abs(road.curvature_at(truck.s)))
        off_sum += abs(truck.offset)
        if abs(offset) < LANE_HALF:
            in_lane += 1
        if (abs(offset) > ROAD_HALF
                or (truck.speed < 0.3 and steps > 60
                    and (road.length - truck.s) > 300.0)):
            off_road += 1
            break
        # career rules (identical in the app): refuel / sleep
        if truck.fuel < REFUEL_BELOW:
            truck.fuel = 1.0
            truck.money -= FUEL_PRICE * TANK_LITERS * (1.0 - REFUEL_BELOW)
            stopped = True
        if truck.fatigue > SLEEP_ABOVE:
            truck.fatigue = 0.0
            truck.money -= 220.0  # hotel
            stopped = True
    km = truck.driven_km
    metrics = {
        "steps": steps,
        "in_lane_pct": in_lane / max(1, steps),
        "finished": docked and steps < max_steps,
        "docked": docked,
        "stop_error_m": stop_error_m,
        "km": km,
        "money": truck.money,
        "stopped_for_rules": stopped,
        "avg_speed": km / max(0.1, steps * DT) * 1000,
        "radar_compliance": (sum(1 for v in radar_pass if v <= SPEED_LIMIT_MPS * 1.05)
                             / max(1, len(radar_pass))),
        "radar_passes": len(radar_pass),
        "max_lat_accel": max_lat,
        "mean_abs_offset": off_sum / max(1, steps),
        "top_speed": max([0.0] + [a for a in [truck.speed]]) if steps else 0.0,
    }
    if record:
        return np.array(feats, dtype=np.float32), np.array(acts, dtype=np.float32), metrics
    return metrics
import types as _types
sim = _types.SimpleNamespace(
    features=features, Road=Road, Truck=Truck, expert=expert,
    run_episode=run_episode, wrap_angle=wrap_angle,
    LOOKAHEAD=LOOKAHEAD, SPEED_LIMIT_MPS=SPEED_LIMIT_MPS,
    REFUEL_BELOW=REFUEL_BELOW, SLEEP_ABOVE=SLEEP_ABOVE,
    ROAD_HALF=ROAD_HALF, LANE_HALF=LANE_HALF, DT=DT,
)

# ===== ets2ai/model.py =====
"""ETS2-AI core: numpy-only MLP + training + export.

Deliberately dependency-free (numpy only) so the exact same numbers can be
reproduced on the CI runner and re-implemented bit-for-bit in Java on the
phone and in TFLite. Deterministic under SEED.
"""
import json
import math
from pathlib import Path
import numpy as np



def init_layers(rng, dtype=np.float32):
    """He initialisation for tanh layers; returns [(W,b), ...]."""
    sizes = [N_IN] + list(HIDDEN) + [N_OUT]
    layers = []
    for i in range(len(sizes) - 1):
        fan_in, fan_out = sizes[i], sizes[i + 1]
        # cast DEPOIS da multiplicacao: com NEP 50 (numpy>=2), float32 * np.float64
        # promoveria para float64 — era o comportamento antigo por acidente.
        w = (rng.standard_normal((fan_in, fan_out)) * np.sqrt(1.0 / fan_in)).astype(dtype)
        b = np.zeros(fan_out, dtype=dtype)
        layers.append((w, b))
    return layers


def forward(x, layers, keep=None):
    """Forward pass. x: (N, N_IN) or (N_IN,). tanh hidden, linear output.

    Precision follows the weights (float32 deploy / float64 experiment).
    `keep` (optional) receives intermediate activations for backprop.
    Returns activations of the output layer.
    """
    a = np.atleast_2d(np.asarray(x, dtype=layers[0][0].dtype))
    last = len(layers) - 1
    for i, (w, b) in enumerate(layers):
        z = a @ w + b
        a = z if i == last else np.tanh(z)
        if keep is not None:
            keep.append(a)
    return a


def mse(pred, target):
    """MSE na precisao nativa dos inputs (float32 fica float32; float64
    conserva a faixa ~1e-308 — usado pelo modo --dtype float64)."""
    p = np.asarray(pred)
    t = np.asarray(target)
    if p.dtype != t.dtype:
        p, t = p.astype(np.float64), t.astype(np.float64)
    return float(np.mean((p - t) ** 2))


class Adam:
    def __init__(self, layers, lr=2e-3, b1=0.9, b2=0.999, eps=1e-8):
        self.lr, self.b1, self.b2, self.eps = lr, b1, b2, eps
        self.m = [[np.zeros_like(p) for p in (w, b)] for (w, b) in layers]
        self.v = [[np.zeros_like(p) for p in (w, b)] for (w, b) in layers]
        self.t = 0

    def step(self, layers, grads):
        self.t += 1
        b1c = 1 - self.b1 ** self.t
        b2c = 1 - self.b2 ** self.t
        for li, ((w, b), (gw, gb)) in enumerate(zip(layers, grads)):
            for pi, (p, g) in enumerate(((w, gw), (b, gb))):
                self.m[li][pi] = self.b1 * self.m[li][pi] + (1 - self.b1) * g
                self.v[li][pi] = self.b2 * self.v[li][pi] + (1 - self.b2) * g * g
                m_hat = self.m[li][pi] / b1c
                v_hat = self.v[li][pi] / b2c
                p -= self.lr * m_hat / (np.sqrt(v_hat) + self.eps)


def train_step(layers, opt, x, y):
    """Um passo de minibatch (Adam + MSE). Usado por train() e pelo treino
    em fluxo (train.py --stream-samples) — fonte unica da matematica."""
    acts = []
    out = forward(x, layers, keep=acts)
    err = out - y                                  # (B, N_OUT)
    grads = [None] * len(layers)
    delta = (2.0 / (len(x) * N_OUT)) * err         # dMSE/dz_out (linear)
    for li in range(len(layers) - 1, -1, -1):
        a_prev = x if li == 0 else acts[li - 1]
        grads[li] = (a_prev.T @ delta, delta.sum(axis=0))
        if li > 0:
            delta = (delta @ layers[li][0].T) * (1 - acts[li - 1] ** 2)
    opt.step(layers, grads)
    return float(np.mean((out - y) ** 2))


def train(x, y, epochs=400, batch=512, lr=2e-3, seed=SEED, verbose=True,
          x_val=None, y_val=None, start_layers=None, dtype=np.float32,
          schedule="cosine"):
    """Train the MLP on (x, y) with Adam + MSE. Returns (layers, history).

    start_layers: optional [(W,b), ...] to continue training from existing
    weights (DAgger finetuning) instead of initialising from scratch.
    dtype: np.float32 (deploy rapido) ou np.float64 (experimento de precisao).
    schedule: "cosine" decai lr de `lr` ate 5% de `lr` ao longo das epocas
    (deterministico, ajuda a fechar a loss); None mantem lr constante.
    """
    rng = np.random.default_rng(seed)
    layers = start_layers if start_layers is not None else init_layers(rng, dtype)
    opt = Adam(layers, lr=lr)
    x = np.asarray(x, dtype=dtype)
    y = np.asarray(y, dtype=dtype)
    if x_val is not None:
        x_val = np.asarray(x_val, dtype=dtype)
        y_val = np.asarray(y_val, dtype=dtype)
    n = len(x)
    history = []
    best = (np.inf, None)
    for epoch in range(epochs):
        if schedule == "cosine":
            opt.lr = lr * (0.05 + 0.95 * 0.5 * (1.0 + math.cos(math.pi * epoch / epochs)))
        idx = rng.permutation(n)
        for s in range(0, n, batch):
            sel = idx[s:s + batch]
            train_step(layers, opt, x[sel], y[sel])
        tr = mse(forward(x, layers), y)
        va = mse(forward(x_val, layers), y_val) if x_val is not None else None
        history.append((tr, va))
        if va is not None and va < best[0]:
            best = (va, [(w.copy(), b.copy()) for (w, b) in layers])
        if verbose and (epoch % 40 == 0 or epoch == epochs - 1):
            msg = f"epoch {epoch:4d}  train_mse {tr:.5f}"
            if va is not None:
                msg += f"  val_mse {va:.5f}"
            print(msg, flush=True)
    if best[1] is not None:  # restore best-validation weights
        layers = best[1]
    return layers, history
# ===== ets2ai/data.py =====
"""Dataset generation: expert demonstrations on random roads.

The expert is a pure-pursuit + predictive-speed controller. Since v0.4.2 the
demonstrations are PERFECT (zero action noise) — the user asked for the
minimum loss mathematically achievable, and the old human-like noise
(sigma=0.02) imposed a ~2e-4 MSE floor that no network could beat.
Train/val roads are disjoint.
"""
import numpy as np


N_TRAIN_ROADS = 220     # v0.4.3: >1M training samples (user spec)
N_VAL_ROADS = 15
NOISE = 0.0            # v0.4.2: especialista perfeito (antes 0.020 humano)
ROAD_SEED = 31337


def _oversample_dock(feats, acts, reps=4):
    """Duplicate approach/dock rows (last 150 m) so the policy learns the
    precise stop: they are a tiny fraction of each episode."""
    tail = feats[:, 11] * 20.0 * 1000.0 < 150.0     # job_left < 150 m
    return (np.concatenate([feats] + [feats[tail]] * (reps - 1)),
            np.concatenate([acts] + [acts[tail]] * (reps - 1)))


def generate():
    x_train, y_train, x_val, y_val = [], [], [], []
    for k in range(N_TRAIN_ROADS + N_VAL_ROADS):
        road = Road.random(ROAD_SEED + k)
        feats, acts, _ = run_episode(
            road,
            lambda r, t, j, rng: expert(r, t, j, noise=NOISE, rng=rng),
            seed=1000 + k, record=True)
        feats, acts = _oversample_dock(feats, acts)
        if k < N_TRAIN_ROADS:
            x_train.append(feats); y_train.append(acts)
        else:
            x_val.append(feats); y_val.append(acts)
    return (np.concatenate(x_train), np.concatenate(y_train),
            np.concatenate(x_val), np.concatenate(y_val))


# ===== ets2ai/train.py =====
"""Train the ETS2-AI driving policy and export weights + metrics.

Usage:  python -m ets2ai.train [--epochs N] [--out DIR]

Reports MSE (the project target is <= 0.150) and closed-loop driving quality
on held-out roads. Deterministic: same seed -> same weights everywhere.
"""
import argparse
import json
from pathlib import Path
import numpy as np



def policy_from_layers(layers):
    def policy(road, truck, job_left_km, rng=None):
        f = np.array(sim.features(road, truck, job_left_km), dtype=np.float32)
        out = forward(f, layers)[0]
        return float(out[0]), float(out[1]), float(out[2])
    return policy


def closed_loop_eval(layers, n_roads=N_VAL_ROADS, seed=777):
    policy = policy_from_layers(layers)
    rows = []
    for k in range(n_roads):
        road = Road.random(ROAD_SEED + 100 + k)   # roads never seen in training
        rows.append(run_episode(road, policy, seed=seed + k))
    n_pass = sum(r["radar_passes"] for r in rows)
    agg = {
        "roads": n_roads,
        "finish_rate": sum(r["finished"] for r in rows) / n_roads,
        "in_lane_pct": sum(r["in_lane_pct"] for r in rows) / n_roads,
        "avg_speed_kmh": sum(r["avg_speed"] for r in rows) / n_roads * 3.6,
        "km_total": sum(r["km"] for r in rows),
        "radar_compliance": (sum(r["radar_passes"] * r["radar_compliance"] for r in rows)
                             / max(1, n_pass)),
        "radar_passes": n_pass,
        "max_lat_accel": max(r["max_lat_accel"] for r in rows),
        "gps_mean_abs_offset_m": sum(r["mean_abs_offset"] for r in rows) / n_roads,
        "dock_rate": sum(1 for r in rows if r["docked"]) / n_roads,
        "mean_stop_error_m": (sum(r["stop_error_m"] for r in rows if r["stop_error_m"] is not None)
                              / max(1, sum(1 for r in rows if r["stop_error_m"] is not None))),
        "top_speed_kmh": max(r["avg_speed"] for r in rows) * 3.6,
    }
    return agg, rows


def train_stream(samples, batch=1024, lr=2e-3, seed=SEED, dtype=np.float64,
                 verbose=True, val_every=2_000_000):
    """Treino em FLUXO: amostras geradas na hora pelo simulador vetorizado
    (ets2ai.vector_gen) — todas unicas, orcamento em # de amostras (nao em
    epocas). Deterministico sob `seed`; cosine LR ao longo do orcamento;
    restaura os melhores pesos de validacao (val fixa, semente 999)."""
    import math as _math
    from . import vector_gen
    from .model import Adam, forward, init_layers, mse, train_step

    rng = np.random.default_rng(seed)
    layers = init_layers(rng, dtype)
    opt = Adam(layers, lr=lr)
    xv, yv = vector_gen.val_set(seed=999, dtype=dtype)
    total_steps = max(1, samples // batch)
    step = 0
    consumed = 0
    last_val = 0
    best = (np.inf, [(w.copy(), b.copy()) for (w, b) in layers])
    for x, y in vector_gen.stream(seed, n_trucks=3072, dtype=dtype):
        if consumed >= samples:
            break
        perm = rng.permutation(len(x))
        for s0 in range(0, len(x), batch):
            sel = perm[s0:s0 + batch]
            if len(sel) < 16:
                continue
            opt.lr = lr * (0.05 + 0.95 * 0.5 *
                           (1.0 + _math.cos(_math.pi * step / total_steps)))
            train_step(layers, opt, x[sel], y[sel])
            step += 1
            consumed += len(sel)
            if consumed >= samples:
                break
        if consumed - last_val >= val_every or consumed >= samples:
            va = mse(forward(xv, layers), yv)
            if va < best[0]:
                best = (va, [(w.copy(), b.copy()) for (w, b) in layers])
            if verbose:
                print(f"      fluxo: {consumed:,} amostras | val {va:.5f}", flush=True)
            last_val = consumed
    layers = best[1]
    return layers, consumed, best[0]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=60,
                    help="60 epocas x ~1M amostras = mesmo orcamento de otimizacao "
                         "das 400 x 120k das versoes anteriores")
    ap.add_argument("--stream-samples", type=int, default=0,
                    help="treino em fluxo com N amostras unicas geradas na hora "
                         "(simulador vetorizado); 0 = modo estatico (epocas)")
    ap.add_argument("--batch", type=int, default=512)
    ap.add_argument("--out", default=str(Path(__file__).resolve().parent.parent / "artifacts"))
    ap.add_argument("--dtype", choices=["float32", "float64"], default="float64",
                    help="float64 = canônico (desde v0.4.1, exigência do usuário); "
                         "float32 = modo rápido/deploy-check")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    dtype = {"float32": np.float32, "float64": np.float64}[args.dtype]

    n_params = (N_IN * HIDDEN[0] + HIDDEN[0]
                + sum(HIDDEN[i] * HIDDEN[i + 1] + HIDDEN[i + 1] for i in range(len(HIDDEN) - 1))
                + HIDDEN[-1] * N_OUT + N_OUT)
    if args.stream_samples > 0:
        print(f"[1/4] treino em FLUXO: {args.stream_samples:,} amostras unicas "
              f"geradas na hora (simulador vetorizado, milhares de caminhoes)...")
        layers, consumed, loss_va = train_stream(
            args.stream_samples, batch=args.batch, dtype=dtype)
        n_samples = consumed
        loss_tr, mae_va = None, None
        print(f"      MSE validacao (fluxo) {loss_va:.5f} (meta <= {LOSS_TARGET})")
    else:
        print("[1/4] gerando dados do especialista (estradas aleatorias)...")
        x_train, y_train, x_val, y_val = generate()
        print(f"      treino {x_train.shape}  val {x_val.shape}")
        n_samples = int(len(x_train) + len(x_val))
        print(f"[2/4] treinando MLP {N_IN}-{'-'.join(str(h) for h in HIDDEN)}-{N_OUT} "
              f"({n_params:,} params, tanh, Adam+cosine, {args.dtype})...")
        layers, hist = train(x_train, y_train, epochs=args.epochs,
                             x_val=x_val, y_val=y_val, dtype=dtype)
        loss_tr = mse(forward(x_train, layers), y_train)
        loss_va = mse(forward(x_val, layers), y_val)
        mae_va = float(np.mean(np.abs(forward(x_val, layers) - y_val)))
        print(f"      MSE treino {loss_tr:.5f} | MSE validacao {loss_va:.5f} "
              f"(meta <= {LOSS_TARGET}) | MAE val {mae_va:.5f}")

    print("[3/4] avaliacao em circuito fechado (estradas ineditas)...")
    agg, rows = closed_loop_eval(layers)
    print(f"      conclusao {agg['finish_rate']*100:.0f}%  "
          f"na faixa {agg['in_lane_pct']*100:.0f}%  "
          f"vel media {agg['avg_speed_kmh']:.0f} km/h")

    print("[4/4] exportando pesos...")
    meta = model_meta(epochs=args.epochs if args.stream_samples == 0 else None,
                      samples=n_samples,
                      loss=loss_va,
                      dtype=args.dtype if args.dtype != "float32" else None)
    save_weights(out / "model-weights.json", layers, meta)
    save_device_format(out / "model-weights.txt", layers, meta)
    (out / "metrics.json").write_text(json.dumps({
        "meta": meta,
        "mse_train": loss_tr,
        "mse_val": loss_va,
        "mae_val": mae_va,
        "loss_target": LOSS_TARGET,
        "target_met": bool(loss_va <= LOSS_TARGET),
        "closed_loop": agg,
        "closed_loop_rows": rows,
    }, indent=2), encoding="utf-8")
    print(f"      -> {out/'model-weights.json'}")
    print(f"      -> {out/'metrics.json'}")
    ok = loss_va <= LOSS_TARGET
    print("META ATINGIDA" if ok else "meta NAO atingida (ver --epochs)")
    return 0 if ok else 1


# ===== ets2ai/vector_gen.py =====
"""Vectorized batch data generator (v0.4.4).

Same expert law as ets2ai/sim.py (pure-pursuit + predictive speed + dock
profile + radar braking), but simulates B trucks on B independent roads in
parallel with numpy — orders of magnitude more samples/s than the scalar
sim. This is what makes "billions of samples" a streaming reality instead
of a 128 GB impossibility: samples are generated on the fly, all unique.

State is path-relative (s, offset, heading_error, speed) — an exact
reformulation of the scalar (x, y, heading)+projection loop while
|offset| (<= 4.6 m) is far below the curve radius (>= 83 m).

Used by `train.py --stream-samples` and by the Kaggle kernel (2x T4).
"""
import numpy as np

# ---- physics (identical to sim.py) ----
DT = 0.1
WHEELBASE = 4.0
MAX_STEER = 0.6
MAX_ACCEL = 1.8
MAX_BRAKE = 3.2
DRAG = 0.030
LAT_ACCEL_ROLLOVER = 3.6
ROLLOVER_MARGIN = 0.82
V_MAX = 36.0
RADAR_SLOW = 0.95
RADAR_BRAKE = 2.6
SPEED_LIMIT = 25.0
PURE_PURSUIT_D = 12.0
LOOKAHEAD = (8.0, 18.0, 40.0, 90.0, 170.0)
FUEL_BURN_IDLE = 0.000012
FUEL_BURN_FULL = 0.000160
FATIGUE_RATE = 1.0 / (11 * 3600)
DOCK_DECEL = 1.6
DOCK_LINE = 6.0          # stop line: length - 6 m
OVERSAMPLE_DOCK_M = 150.0
OVERSAMPLE_REPS = 4      # matches data.py _oversample_dock

# ---- vector roads ----
SEG_LEN = 150.0
N_SEG = 72               # ~10.8 km routes (scalar avg ~9.6 km)
MAX_CURV = 0.012
P_STRAIGHT = 0.35
N_RADARS = 8

CHUNK_ROWS = 262_144     # rows per yielded chunk (~16 MB float32)


def _make_roads(rng, n):
    """Vector roads: curvature (n, N_SEG), radar positions (n, N_RADARS)."""
    curv = rng.uniform(-MAX_CURV, MAX_CURV, (n, N_SEG)).astype(np.float64)
    straight = rng.random((n, N_SEG)) < P_STRAIGHT
    curv[straight] = 0.0
    # radars: first at 700 m, then every U(1500, 2800) — like sim.py
    radars = np.full((n, N_RADARS), np.inf)
    pos = np.full(n, 700.0)
    for r in range(N_RADARS):
        radars[:, r] = pos
        pos = pos + rng.uniform(1500.0, 2800.0, n)
    length = SEG_LEN * N_SEG
    radars[radars > length - 150.0] = np.inf
    return curv, radars, length


def _speed_profile(curv):
    """Allowed speed at each segment START, planning against curves the way
    the scalar expert does: only within its ~260 m lookahead horizon
    (upcoming_curves max_dist). With SEG_LEN=150 that is the next 2 segments."""
    a_lat = LAT_ACCEL_ROLLOVER * ROLLOVER_MARGIN
    with np.errstate(divide="ignore"):
        vc = np.where(np.abs(curv) > 1e-6,
                      np.sqrt(a_lat / np.maximum(np.abs(curv), 1e-9)), V_MAX)
    vc = np.minimum(vc, V_MAX)
    vs = vc.copy()
    # constraint from the NEXT segment's start (150 m away, 12 m brake margin)
    nxt = np.sqrt(np.pad(vc, ((0, 0), (0, 1)), mode="edge")[:, 1:] ** 2
                  + 2.0 * RADAR_BRAKE * max(0.0, SEG_LEN - 12.0))
    vs = np.minimum(vs, nxt)
    return vs


class _Fleet:
    """B trucks stepping in lockstep on B roads."""

    def __init__(self, rng, n):
        self.n = n
        self.curv, self.radars, self.length = _make_roads(rng, n)
        self.vs = _speed_profile(self.curv)
        self.reset(rng)

    def reset(self, rng):
        n = self.n
        # posicoes iniciais ALEATORIAS ao longo da estrada: a frota fica
        # permanentemente misturada (como episodios independentes do escalar)
        self.s = rng.uniform(5.0, self.length - 600.0, n)
        self.offset = rng.uniform(-2.0, 2.0, n)
        idx = np.clip((self.s / SEG_LEN).astype(np.int64), 0, N_SEG - 1)
        v_allow0 = self.vs[np.arange(n), idx]
        self.speed = np.minimum(rng.uniform(8.0, 22.0, n), v_allow0)
        self.hdg_err = rng.uniform(-0.25, 0.25, n)
        self.steer_pos = np.zeros(n)
        self.fuel = np.ones(n)
        self.fatigue = np.zeros(n)

    def _kappa_at(self, s):
        idx = np.clip((s / SEG_LEN).astype(np.int64), 0, N_SEG - 1)
        return self.curv[np.arange(self.n), idx], idx

    def step_expert(self):
        """One DT step: expert actions + truck physics. Returns (feats, acts)."""
        n = self.n
        ar = np.arange(n)
        k_now, idx = self._kappa_at(self.s)
        # --- pure pursuit steering ---
        alpha = np.arctan2(-self.offset, PURE_PURSUIT_D) - self.hdg_err
        steer = np.clip(2.0 * np.sin(alpha), -1.0, 1.0)
        # --- speed target: curves (backward profile), dock, radar, fatigue ---
        seg_start = idx * SEG_LEN
        v_next = self.vs[ar, np.minimum(idx + 1, N_SEG - 1)]
        d_next = seg_start + SEG_LEN - self.s
        v_allow = np.sqrt(v_next ** 2 + 2.0 * RADAR_BRAKE * np.maximum(0.0, d_next - 12.0))
        a_lat = LAT_ACCEL_ROLLOVER * ROLLOVER_MARGIN
        v_curve_now = np.where(np.abs(k_now) > 1e-6,
                               np.sqrt(a_lat / np.maximum(np.abs(k_now), 1e-9)), V_MAX)
        v_target = np.minimum(np.minimum(V_MAX, v_curve_now), v_allow)
        # dock profile
        d_dock = (self.length - DOCK_LINE) - self.s
        v_target = np.minimum(v_target, np.sqrt(2.0 * DOCK_DECEL * np.maximum(0.0, d_dock)))
        # radar
        d_radar = np.min(np.where(self.radars > self.s[:, None],
                                  self.radars - self.s[:, None], np.inf), axis=1)
        d_radar = np.minimum(d_radar, 500.0)
        v_radar = SPEED_LIMIT * RADAR_SLOW
        brake_dist = np.maximum(0.0, self.speed ** 2 - v_radar ** 2) / (2.0 * RADAR_BRAKE) + 25.0
        v_target = np.where(d_radar < brake_dist, np.minimum(v_target, v_radar), v_target)
        # fatigue easing
        v_target = v_target * (1.0 - 0.08 * self.fatigue)
        v_target = np.where(v_target < 0.4, 0.0, v_target)
        dv = v_target - self.speed
        throttle = np.clip(dv / 1.8, 0.0, 1.0)
        brake = np.clip(-dv / 2.6, 0.0, 1.0)
        # --- features (contract, in order) ---
        feats = np.empty((n, 13))
        feats[:, 0] = self.speed / 25.0
        feats[:, 1] = self.offset / 3.5
        feats[:, 2] = self.hdg_err / 0.6
        for j, d in enumerate(LOOKAHEAD):
            feats[:, 3 + j] = self._kappa_at(self.s + d)[0] / 0.05
        feats[:, 8] = SPEED_LIMIT / 25.0
        feats[:, 9] = self.fuel
        feats[:, 10] = self.fatigue
        feats[:, 11] = np.minimum((self.length - self.s) / 1000.0, 20.0) / 20.0
        feats[:, 12] = d_radar / 500.0
        acts = np.stack([steer, throttle, brake], axis=1)
        # --- truck physics (path-relative, same law as Truck.step) ---
        self.steer_pos += np.clip(steer - self.steer_pos, -0.15, 0.15)
        wheel = self.steer_pos * MAX_STEER
        ds = self.speed * np.cos(self.hdg_err) * DT
        self.hdg_err += (self.speed / WHEELBASE) * np.tan(wheel) * DT \
            - self.speed * np.cos(self.hdg_err) * k_now * DT
        self.offset += self.speed * np.sin(self.hdg_err) * DT
        self.s += ds
        self.speed = np.maximum(0.0, self.speed +
                                (throttle * MAX_ACCEL - brake * MAX_BRAKE
                                 - DRAG * self.speed) * DT)
        self.fuel = np.maximum(0.0, self.fuel - DT *
                               (FUEL_BURN_IDLE + throttle * (FUEL_BURN_FULL - FUEL_BURN_IDLE)))
        self.fatigue = np.minimum(1.0, self.fatigue + DT * FATIGUE_RATE)
        return feats, acts

    def alive(self):
        return (self.s < self.length - DOCK_LINE) & (np.abs(self.offset) <= 4.6)


def stream(seed, n_trucks=3072, dtype=np.float32):
    """Yields (x, y) chunks of fresh expert demonstrations, forever.
    Deterministic under `seed`. All samples unique (roads regenerate)."""
    rng = np.random.default_rng(seed)
    fleet = _Fleet(rng, n_trucks)
    buf_x, buf_y = [], []
    rows = 0
    while True:
        feats, acts = fleet.step_expert()
        alive = fleet.alive()
        if alive.any():
            fx, ay = feats[alive], acts[alive]
            dock_mask = ((fleet.length - DOCK_LINE) - fleet.s[alive]) < OVERSAMPLE_DOCK_M
            if dock_mask.any():
                fx = np.concatenate([fx] + [fx[dock_mask]] * (OVERSAMPLE_REPS - 1))
                ay = np.concatenate([ay] + [ay[dock_mask]] * (OVERSAMPLE_REPS - 1))
            buf_x.append(fx.astype(dtype))
            buf_y.append(ay.astype(dtype))
            rows += len(fx)
        if (~alive).any():
            # restart the finished trucks at random positions (mixed fleet)
            done = np.where(~alive)[0]
            r2 = np.random.default_rng(rng.integers(0, 2**63))
            fleet.s[done] = r2.uniform(5.0, fleet.length - 600.0, len(done))
            fleet.offset[done] = r2.uniform(-2.0, 2.0, len(done))
            idx = np.clip((fleet.s[done] / SEG_LEN).astype(np.int64), 0, N_SEG - 1)
            fleet.speed[done] = np.minimum(r2.uniform(8.0, 22.0, len(done)),
                                           fleet.vs[done, idx])
            fleet.hdg_err[done] = r2.uniform(-0.25, 0.25, len(done))
            fleet.steer_pos[done] = 0.0
            fleet.fuel[done] = 1.0
            fleet.fatigue[done] = 0.0
            # fresh roads for the restarted trucks
            c2, r2r, _ = _make_roads(np.random.default_rng(rng.integers(0, 2**63)), len(done))
            fleet.curv[done] = c2
            fleet.radars[done] = r2r
            fleet.vs[done] = _speed_profile(c2)
        if rows >= CHUNK_ROWS:
            yield np.concatenate(buf_x), np.concatenate(buf_y)
            buf_x, buf_y, rows = [], [], 0


def val_set(seed=999, n_trucks=384, max_rows=131072, dtype=np.float32):
    """Fixed validation set from a held-out stream (different seed)."""
    gen = stream(seed, n_trucks=n_trucks, dtype=dtype)
    x, y = next(gen)
    return x[:max_rows], y[:max_rows]


# ---------------------------------------------------------------------------
# Kaggle runner footer (appended by build_kernel.py — do not edit here)
# v0.4.4: treino em FLUXO com o simulador vetorizado — orcamento de AMOSTRAS
# (1 bilhao por padrao, FP32 nas T4; FP64 via ETS2AI_F64=1 com orcamento menor)
# ---------------------------------------------------------------------------
import json as _json
import math as _math
import os as _os
import time as _time

_OUT = _os.environ.get("KAGGLE_WORKING_DIR", ".")
_F64 = _os.environ.get("ETS2AI_F64") == "1"
_DTYPE = np.float64 if _F64 else np.float32
_SAMPLES = int(_os.environ.get("ETS2AI_SAMPLES", "1000000000"))
_MAX_SEC = float(_os.environ.get("ETS2AI_MAX_SECONDS", "10800"))
_BATCH = int(_os.environ.get("ETS2AI_BATCH", "4096" if not _F64 else "1024"))
_EPOCHS = int(_os.environ.get("ETS2AI_EPOCHS", "60"))
_n_params = (N_IN * HIDDEN[0] + HIDDEN[0]
             + sum(HIDDEN[i] * HIDDEN[i + 1] + HIDDEN[i + 1] for i in range(len(HIDDEN) - 1))
             + HIDDEN[-1] * N_OUT + N_OUT)
print(f"[kaggle] arquitetura {N_IN}-{'-'.join(str(_h) for _h in HIDDEN)}-{N_OUT} "
      f"({_n_params:,} params) | dtype {_DTYPE.__name__} | batch {_BATCH}")
print(f"[kaggle] orcamento: {_SAMPLES:,} amostras em fluxo (unicas) | "
      f"teto {_MAX_SEC/3600:.1f} h")

_gpus = []
_TRAIN_GPU = False
try:
    import tensorflow as _tf
    _gpus = _tf.config.list_physical_devices("GPU")
except Exception:
    _tf = None

if _tf is not None and len(_gpus) >= 1:
    # ---------------- GPU PATH (2x T4, MirroredStrategy, fluxo) ----------------
    if _DTYPE == np.float64:
        _tf.keras.backend.set_floatx("float64")
    print(f"[kaggle] GPU detectada: {len(_gpus)}x {_gpus[0][1]} — "
          f"tf.distribute.MirroredStrategy (todas as GPUs), {_DTYPE.__name__}")
    _total_steps = max(1, _SAMPLES // _BATCH)
    _pi = _tf.constant(_math.pi, _tf.float32)

    class _CosineFloor(_tf.keras.optimizers.schedules.LearningRateSchedule):
        def __init__(self, base, total):
            super().__init__()
            self.base = base
            self.total = total
        def __call__(self, step):
            f = _tf.minimum(_tf.cast(step, _tf.float32) / self.total, 1.0)
            return self.base * (0.05 + 0.95 * 0.5 * (1.0 + _tf.cos(_pi * f)))

    _strategy = _tf.distribute.MirroredStrategy()
    with _strategy.scope():
        _model = _tf.keras.Sequential()
        _model.add(_tf.keras.Input(shape=(N_IN,)))
        for _h in HIDDEN:
            _model.add(_tf.keras.layers.Dense(
                _h, activation="tanh", kernel_initializer="he_normal"))
        _model.add(_tf.keras.layers.Dense(
            N_OUT, activation="linear", kernel_initializer="he_normal"))
        _model.compile(_tf.keras.optimizers.Adam(learning_rate=_CosineFloor(2e-3, _total_steps)), loss="mse")
    _xva, _yva = val_set(seed=999)
    _t0 = _time.time()
    _consumed = 0
    _best_val = float("inf")
    _best_w = None
    _last_val = 0
    print("[kaggle] gerando dados em fluxo e treinando...")
    for _x, _y in stream(SEED, n_trucks=3072):
        if _consumed >= _SAMPLES or (_time.time() - _t0) > _MAX_SEC:
            break
        for _s0 in range(0, len(_x), _BATCH):
            _mb_x = _x[_s0:_s0 + _BATCH]
            _mb_y = _y[_s0:_s0 + _BATCH]
            if len(_mb_x) < 64:
                continue
            _model.train_on_batch(_mb_x.astype(_DTYPE), _mb_y.astype(_DTYPE))
            _consumed += len(_mb_x)
            if _consumed >= _SAMPLES or (_time.time() - _t0) > _MAX_SEC:
                break
        if _consumed - _last_val >= 20_000_000 or _consumed >= _SAMPLES                 or (_time.time() - _t0) > _MAX_SEC:
            _va = float(_model.evaluate(_xva.astype(_DTYPE), _yva.astype(_DTYPE),
                                        verbose=0, batch_size=8192))
            if _va < _best_val:
                _best_val = _va
                _best_w = _model.get_weights()
            _h_elapsed = (_time.time() - _t0) / 3600
            print(f"[kaggle] {_consumed:,} amostras | val {_va:.5f} "
                  f"(melhor {_best_val:.5f}) | {_h_elapsed:.2f} h", flush=True)
            _last_val = _consumed
    if _best_w is not None:
        _model.set_weights(_best_w)          # restaura os melhores pesos
    _w = _model.get_weights()
    _layers = [(np.asarray(_w[2 * i], dtype=_DTYPE),
                np.asarray(_w[2 * i + 1], dtype=_DTYPE))
               for i in range(len(_w) // 2)]
    _TRAIN_GPU = True
    _loss_tr = None
    _loss_va = _best_val
else:
    # ---------------- CPU fallback (deterministico, estatico) ----------------
    print(f"[kaggle] sem GPU — treinando em numpy (CPU, {_DTYPE.__name__}, "
          f"dataset estatico)")
    _xtr, _ytr, _xva, _yva = generate()
    _xtr = np.asarray(_xtr, dtype=_DTYPE); _ytr = np.asarray(_ytr, dtype=_DTYPE)
    _xva = np.asarray(_xva, dtype=_DTYPE); _yva = np.asarray(_yva, dtype=_DTYPE)
    print(f"[kaggle] treino {_xtr.shape} | val {_xva.shape}")
    _layers, _hist = train(_xtr, _ytr, epochs=_EPOCHS, x_val=_xva, y_val=_yva,
                           dtype=_DTYPE)
    _consumed = int(len(_xtr) + len(_xva))
    _loss_tr = mse(forward(_xtr, _layers), _ytr)
    _loss_va = mse(forward(_xva, _layers), _yva)

print(f"[kaggle] MSE validacao {_loss_va:.5f} (meta <= {LOSS_TARGET}) | "
      f"amostras consumidas: {_consumed:,}")

_agg, _rows = closed_loop_eval(_layers, n_roads=5)
print(f"[kaggle] circuito fechado: {_agg['finish_rate']*100:.0f}% rotas, "
      f"{_agg['in_lane_pct']*100:.0f}% faixa, {_agg['avg_speed_kmh']:.0f} km/h, "
      f"{_agg['radar_compliance']*100:.0f}% radares, {_agg['dock_rate']*100:.0f}% dock")

save_weights(_os.path.join(_OUT, "model-weights.json"), _layers,
             model_meta(epochs=None, samples=int(_consumed), loss=_loss_va,
                        dtype="float64" if _DTYPE == np.float64 else None))
with open(_os.path.join(_OUT, "metrics.json"), "w", encoding="utf-8") as _f:
    _json.dump({"mse_train": _loss_tr, "mse_val": _loss_va,
                "loss_target": LOSS_TARGET, "closed_loop": _agg,
                "trained_on_gpu": _TRAIN_GPU, "n_gpus": len(_gpus),
                "samples_consumed": int(_consumed),
                "dtype": _DTYPE.__name__,
                "streaming": bool(_TRAIN_GPU)}, _f, indent=2)
print(f"[kaggle] saida: model-weights.json + metrics.json (gpu={_TRAIN_GPU}, "
      f"ngpus={len(_gpus)}, dtype={_DTYPE.__name__}, "
      f"amostras={_consumed:,}, streaming={_TRAIN_GPU})")

