#!/bin/sh
# Host-tool stubs so we can build Linux without bison/flex/libelf/openssl-dev/bc.
set -e
L=/home/user/5/build/linux
H=/home/user/5/build/host
mkdir -p "$H/bin" "$L/tools/objtool" "$L/scripts" "$L/certs"

# bc that implements kernel/time/timeconst.bc
cat > "$H/bin/bc" << 'PY'
#!/usr/bin/env python3
import math, sys, pathlib

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def fmul(b, n, d):
    return (pow(2, b) * n + d - 1) // d

def fadj(b, n, d):
    d = d // gcd(n, d)
    return pow(2, b) * (d - 1) // d

def fmuls(b, n, d):
    s = 0
    while True:
        m = fmul(s, n, d)
        if m >= pow(2, b - 1):
            return s
        s += 1

def timeconst(hz):
    out = []
    p = out.append
    p("/* Automatically generated by kernel/time/timeconst.bc */")
    p("/* Time conversion constants for HZ == %d */" % hz)
    p("")
    p("#ifndef KERNEL_TIMECONST_H")
    p("#define KERNEL_TIMECONST_H")
    p("")
    p("#include <linux/param.h>")
    p("#include <linux/types.h>")
    p("")
    p("#if HZ != %d" % hz)
    p("#error \"include/generated/timeconst.h has the wrong HZ value!\"")
    p("#endif")
    p("")
    if hz < 2:
        p("#error Totally bogus HZ value!")
    else:
        s = fmuls(32, 1000, hz)
        p("#define HZ_TO_MSEC_MUL32\tU64_C(0x%x)" % fmul(s, 1000, hz))
        p("#define HZ_TO_MSEC_ADJ32\tU64_C(0x%x)" % fadj(s, 1000, hz))
        p("#define HZ_TO_MSEC_SHR32\t%d" % s)
        s = fmuls(32, hz, 1000)
        p("#define MSEC_TO_HZ_MUL32\tU64_C(0x%x)" % fmul(s, hz, 1000))
        p("#define MSEC_TO_HZ_ADJ32\tU64_C(0x%x)" % fadj(s, hz, 1000))
        p("#define MSEC_TO_HZ_SHR32\t%d" % s)
        cd = gcd(hz, 1000)
        p("#define HZ_TO_MSEC_NUM\t\t%d" % (1000 // cd))
        p("#define HZ_TO_MSEC_DEN\t\t%d" % (hz // cd))
        p("#define MSEC_TO_HZ_NUM\t\t%d" % (hz // cd))
        p("#define MSEC_TO_HZ_DEN\t\t%d" % (1000 // cd))
        p("")
        s = fmuls(32, 1000000, hz)
        p("#define HZ_TO_USEC_MUL32\tU64_C(0x%x)" % fmul(s, 1000000, hz))
        p("#define HZ_TO_USEC_ADJ32\tU64_C(0x%x)" % fadj(s, 1000000, hz))
        p("#define HZ_TO_USEC_SHR32\t%d" % s)
        s = fmuls(32, hz, 1000000)
        p("#define USEC_TO_HZ_MUL32\tU64_C(0x%x)" % fmul(s, hz, 1000000))
        p("#define USEC_TO_HZ_ADJ32\tU64_C(0x%x)" % fadj(s, hz, 1000000))
        p("#define USEC_TO_HZ_SHR32\t%d" % s)
        cd = gcd(hz, 1000000)
        p("#define HZ_TO_USEC_NUM\t\t%d" % (1000000 // cd))
        p("#define HZ_TO_USEC_DEN\t\t%d" % (hz // cd))
        p("#define USEC_TO_HZ_NUM\t\t%d" % (hz // cd))
        p("#define USEC_TO_HZ_DEN\t\t%d" % (1000000 // cd))
        cd = gcd(hz, 1000000000)
        p("#define HZ_TO_NSEC_NUM\t\t%d" % (1000000000 // cd))
        p("#define HZ_TO_NSEC_DEN\t\t%d" % (hz // cd))
        p("#define NSEC_TO_HZ_NUM\t\t%d" % (hz // cd))
        p("#define NSEC_TO_HZ_DEN\t\t%d" % (1000000000 // cd))
        p("")
        p("#endif /* KERNEL_TIMECONST_H */")
    sys.stdout.write("\n".join(out) + "\n")

args = [a for a in sys.argv[1:] if a not in ("-q", "-l")]
src = None
for a in args:
    if a.endswith(".bc"):
        src = a
data = sys.stdin.read() if not sys.stdin.isatty() else ""
hz = None
for tok in data.replace("\n", " ").split():
    if tok.isdigit():
        hz = int(tok)
        break
if hz is None:
    hz = 1000
if src and "timeconst" in src:
    timeconst(hz)
    sys.exit(0)
# generic fallback
print(hz)
PY
chmod 755 "$H/bin/bc"

# objtool stub
cat > "$L/tools/objtool/objtool" << 'EOF'
#!/bin/sh
exit 0
EOF
chmod 755 "$L/tools/objtool/objtool"
# stop Makefile from trying to compile objtool
if grep -q '^prepare: tools/objtool' "$L/Makefile"; then
    sed -i 's/^prepare: tools\/objtool/prepare:/' "$L/Makefile"
fi

# extract-cert stub (no libcrypto headers)
cat > "$L/certs/extract-cert.c" << 'EOF'
int main(int argc, char **argv) { (void)argc; (void)argv; return 0; }
EOF

# sorttable stub — used if BUILDTIME_TABLE_SORT
if [ -f "$L/scripts/sorttable.c" ]; then
    cat > "$L/scripts/sorttable.c" << 'EOF'
int main(void) { return 0; }
EOF
fi

# kconfig conf stub so "make syncconfig" does not need bison
mkdir -p "$L/scripts/kconfig"
cat > "$L/scripts/kconfig/conf" << 'EOF'
#!/bin/sh
# Regenerated headers already exist; succeed quietly.
exit 0
EOF
chmod 755 "$L/scripts/kconfig/conf"

echo "stubs ready"
